version: '3.9'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    networks:
      - main
  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./src
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - main

volumes:
  db:
networks:
  main:
